### ISSUE TITLE
URLs not quite right

### ISSUE THREAD

**Issue by devenblake** [nadimkobeissi/appleprivacyletter#3769]
I took a glance at the letter and it looks like there are some instances of URLs getting screwed up.

Minteck, who is right now signer 1986, has their URL listed as "https://Twitter: @_Minteck".

My signature (issue #2394) hyperlinks to my GitHub rather than my personal website, which is annoying because GitHub is a proprietary service by which I'd prefer not to be represented, and I'm sure others will have this issue.

Robert Stark (issue #3620)'s entry hyperlinks to https://appleprivacyletter.com/BigCat.ceo rather than their website, that they listed, BigCat.ceo.

Remko Tronçon (issue #3618)'s entry hyperlinks to their GitHub rather than their website, https://mko.re, which redirects to https://el-tramo.be/.

Edmund Edgar (issue #3616) has the same issue as Stark's.

And so on. I only looked at a handful of closed issues to find these, so I'd think that this is pretty common.

**Comment by devenblake** [comment]
Suggested fix: A clearer issue template that tells the user that they must put a correctly-formatted hyperlink in the URL box. Also, always accept users' URLs, even if there's something funny going on (such as Remko's site), because malicious links are representative of the user that submitted them and not the letter itself.

**Comment by devenblake** [comment]
CC @nadimkobeissi

**Comment by nadimkobeissi** [comment]
Pull requests welcome.
