### ISSUE TITLE
Is the phrasing correct?

### ISSUE THREAD

**Issue by digitalblossom** [nadimkobeissi/appleprivacyletter#3917]
Are you sure the methodology you outline in the letter is accurate? Because 
A. [in Apple's technical paper](https://www.apple.com/child-safety/pdf/CSAM_Detection_Technical_Summary.pdf) it nowhere mentions iMessage
B. it does not continously monitor (quote) `photos saved or shared on the user's iPhone, iPad, or Mac` but those uploaded to iCloud. That doesn't necessarily have anything to do with sharing and also not with saving something on device.

**Comment by nadimkobeissi** [comment]
https://www.apple.com/child-safety/

**Comment by digitalblossom** [comment]
> https://www.apple.com/child-safety/


> When a child receives this type of content the photo will be blurred and the
> child will be warned, presented with helpful resources, and reassured it is okay
> if they do not want to view this photo. As an additional precaution the child can
> also be told that, to make sure they are safe, their parents will get a message
> if they do view it

> The feature is designed so that Apple does not get access to the messages.

This seems as little invasive as it gets to me, given the entire thing is optional. But opinions differ
