### ISSUE TITLE
Add alternate signing method

### ISSUE THREAD

**Issue by EthanTheInnovator** [nadimkobeissi/appleprivacyletter#4309]
Using GitHub is fine for devs, but the average person does not have a GitHub account. Most will not want to crest an account just to sign a petition. I believe this severely bottlenecks the number of people we can get to sign this petition, as it basically limits it to the developer community.

**Comment by EthanTheInnovator** [comment]
Alternatively, we could move this to a Change.org petition, but that would mean losing all of the signatures we already have. Implementing a new system for signatures (maybe a google form?) would allow us to keep old signatures. As the petition gets bigger though, I am unsure as to how that would scale.

**Comment by nadimkobeissi** [comment]
Pull requests welcome
