### ISSUE TITLE
[SIGN] Speed

### ISSUE THREAD

**Issue by CertifiedRascal** [nadimkobeissi/appleprivacyletter#445]
### Name

Speed

### Affiliation

Rails Developer and Software Company Owner

### 

- [ ] I am signing as an organization.

**Comment by CertifiedRascal** [comment]
@georgio Wait why was this labeled as "invalid"?

**Comment by georgio** [comment]
We would appreciate it if you could share your name to be added to the petition

**Comment by CertifiedRascal** [comment]
@georgio Ha that is my name actually. I would prefer not to do first and last, but I suppose I can if it's wanted. I did notice some others using handles as well, though.

**Comment by georgio** [comment]
Oh alright, I'm sorry I assumed it was a pseudonym. It's fine in this case, will be added shortly.

**Comment by CertifiedRascal** [comment]
@georgio Thanks Georgio! Have a good one and thanks for doing this
