### ISSUE TITLE
fairmania[SIGN] Your Name Here

### ISSUE THREAD

**Issue by fairmania** [nadimkobeissi/appleprivacyletter#5452]
### Name

Roger Fairman

### 

- [ ] I am signing as an organization.

**Comment by fairmania** [comment]
How many will have their beach photos flagged as obscene due to the people only wearing swimwear. How much time and how many reputations will be lost because of this! This is a rabbit-hole we cannot venture down with current technology

**Comment by cyberrrr** [comment]
> How many will have their beach photos flagged as obscene due to the people only wearing swimwear. How much time and how many reputations will be lost because of this! This is a rabbit-hole we cannot venture down with current technology

Your specific beach photos aren't in the CSAM database is it?
