### ISSUE TITLE
Ed Carter

### ISSUE THREAD

**Issue by universegit** [nadimkobeissi/appleprivacyletter#596]
### Name

Ed Carter

### 

- [X] I am signing as an organization.

**Comment by universegit** [comment]
This new practice by Apple exposes the vulnerability of encrypted data stored in iCloud. The Apple user does not have a private key only available to that user, but rather Apple can access that key to access the clear text or graphics in the user's encrypted data on iCloud. That's like very little security at all. All of the Apple's bragging about keeping your data private crumbles into dust.

**Comment by georgio** [comment]
What organization are you signing as?
