### ISSUE TITLE
Hi, I might have filled out the form wrong, I am signing as an organization (called Swivro) but I believe you added me as an individual.

### ISSUE THREAD

**Issue by kasperireland** [nadimkobeissi/appleprivacyletter#6750]
Hi, I might have filled out the form wrong, I am signing as an organization (called Swivro) but I believe you added me as an individual.

_Originally posted by @kasperireland in https://github.com/nadimkobeissi/appleprivacyletter/issues/6091#issuecomment-895223077_

**Comment by datenreisen** [comment]
The same here:

https://github.com/nadimkobeissi/appleprivacyletter/issues/7060

Please add «Digital Society Switzerland» to the list of organizations. Thanks!

**Comment by AltusWebsites** [comment]
Yeah, I signed up as Altus Websites, LLC on issue #6206 and was mistakenly added as an individual. Anyways, thanks for supporting this cause and you're work!
