### ISSUE TITLE
Missing signatures?

### ISSUE THREAD

**Issue by Cryptosaurus** [nadimkobeissi/appleprivacyletter#6872]
It seems that a number of signatures in the batch #623 to #700 (commit 6b0f5be) were not added to the list (eg #627 #629 #642 #646 ... -- #627 signed again as #1486).
Did you consider them invalid, or is it just a mistake?
Thanks for doing this in any case, I assume it's a lot of tedious work...

**Comment by nadimkobeissi** [comment]
Sorry, this was a mistake. I'm looking into it now.
