### ISSUE TITLE
[SIGN] Kushal Das

### ISSUE THREAD

**Issue by kushaldas** [nadimkobeissi/appleprivacyletter#799]
### Name

Kushal Das

### Affiliation

Freedom of the Press Foundation

### Website/Twitter/etc.

https://twitter.com/kushaldas

### 

- [ ] I am signing as an organization.

**Comment by kushaldas** [comment]
Q: Even though the commit closes this issue, my name never showed up (the commit does not have my name), @nadimkobeissi can you please have a look?

**Comment by iSergio18** [comment]
It will be added shortly
