### ISSUE TITLE
[SIGN] Your Name Here

### ISSUE THREAD

**Issue by Subsentient** [nadimkobeissi/appleprivacyletter#8481]
### Name

Daniel Hopson

### 

- [ ] I am signing as an organization.

**Comment by Subsentient** [comment]
"The trouble with fighting for human freedom is that one spends most of one's time defending scoundrels. For it is against scoundrels that oppressive laws are first aimed, and oppression must be stopped at the beginning if it is to be stopped at all." -H. Mencken

**Comment by mckinley360** [comment]
Terrific quote. I'll be using that.
